"""added flag reason row

Revision ID: b7b0eaa11bd4
Revises: ab243fe98c38
Create Date: 2026-04-28 19:47:42.709278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b0eaa11bd4'
down_revision: Union[str, Sequence[str], None] = 'ab243fe98c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('flag_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'flag_reason')
    # ### end Alembic commands ###
